### ISSUE TITLE
Lightbar color on activated

### ISSUE THREAD

**Issue by Odizinne** [yesbotics/dualsense-controller-python#6]
Hello, thank you for this project!

Is there a way to avoiding setting lightbar color (to green) when activating controller?

i would like to be able to not interfere with it (if lightbar was 0, 0, 255 when activating, do not override it)

**Comment by einspunktnull** [comment]
Unfortunately, it is not possible for me to read out the previous status of some properties, such as the lightbar, and set them initially. I have therefore changed the library so that the initial value of the lightbar is off or black and no longer green.
This adjustment is part of the latest version [0.3.0](https://github.com/yesbotics/dualsense-controller-python/tree/0.3.0).
